### ISSUE TITLE
TypeError in getIdentifierLoc 

### ISSUE THREAD

**Issue by PEM--** [wangtao0101/vscode-js-import#2]
import React, { PureComponent } from 'react'
import { storiesOf } from '@storybook/react'
import { SingleDatePicker } from 'react-dates'
import 'react-dates/lib/css/_datepicker.css'

class Tester extends PureComponent

storiesOf('Custom/react-dates', module)
  .add('default', () => (
    <p>Testing react-dates</p>
  ))

TypeError: Cannot read property '0' of null
    at getIdentifierLoc (/Users/pem/.vscode/extensions/wangtao0101.vscode-js-import-0.11.3/node_modules/parse-import-es6/dist/parseImport.js:131:23)
    at /Users/pem/.vscode/extensions/wangtao0101.vscode-js-import-0.11.3/node_modules/parse-import-es6/dist/parseImport.js:159:33
    at Array.forEach (native)
    at getAllIdentifierLoc (/Users/pem/.vscode/extensions/wangtao0101.vscode-js-import-0.11.3/node_modules/parse-import-es6/dist/parseImport.js:156:22)
    at mapCommentsToIdentifier (/Users/pem/.vscode/extensions/wangtao0101.vscode-js-import-0.11.3/node_modules/parse-import-es6/dist/parseImport.js:172:26)
    at mapCommentsToImport (/Users/pem/.vscode/extensions/wangtao0101.vscode-js-import-0.11.3/node_modules/parse-import-es6/dist/parseImport.js:268:26)
    at /Users/pem/.vscode/extensions/wangtao0101.vscode-js-import-0.11.3/node_modules/parse-import-es6/dist/parseImport.js:287:36
    at Array.forEach (native)
    at Object.parseImport [as default] (/Users/pem/.vscode/extensions/wangtao0101.vscode-js-import-0.11.3/node_modules/parse-import-es6/dist/parseImport.js:286:13)
    at ImportFixer.resolveImport (/Users/pem/.vscode/extensions/wangtao0101.vscode-js-import-0.11.3/out/src/importFixer.js:138:51)

**Comment by wangtao0101** [comment]
@PEM-- 
Thank you for reporting the problem.
