### ISSUE TITLE
bug about '$$' 

### ISSUE THREAD

**Issue by hitbear518** [wangtao0101/vscode-js-import#5]
import { $$ } from './foo';
a

TypeError: Cannot read property '0' of null
	at getIdentifierLoc (/Users/sen/.vscode/extensions/wangtao0101.vscode-js-import-0.12.0/node_modules/parse-import-es6/dist/parseImport.js:138:23)
	at /Users/sen/.vscode/extensions/wangtao0101.vscode-js-import-0.12.0/node_modules/parse-import-es6/dist/parseImport.js:166:33
	at Array.forEach (native)
	at getAllIdentifierLoc (/Users/sen/.vscode/extensions/wangtao0101.vscode-js-import-0.12.0/node_modules/parse-import-es6/dist/parseImport.js:163:22)
	at mapCommentsToIdentifier (/Users/sen/.vscode/extensions/wangtao0101.vscode-js-import-0.12.0/node_modules/parse-import-es6/dist/parseImport.js:179:26)
	at mapCommentsToImport (/Users/sen/.vscode/extensions/wangtao0101.vscode-js-import-0.12.0/node_modules/parse-import-es6/dist/parseImport.js:275:26)
	at /Users/sen/.vscode/extensions/wangtao0101.vscode-js-import-0.12.0/node_modules/parse-import-es6/dist/parseImport.js:294:36
	at Array.forEach (native)
	at Object.parseImport [as default] (/Users/sen/.vscode/extensions/wangtao0101.vscode-js-import-0.12.0/node_modules/parse-import-es6/dist/parseImport.js:293:13)
	at ImportFixer.resolveImport (/Users/sen/.vscode/extensions/wangtao0101.vscode-js-import-0.12.0/out/src/importFixer.js:140:51)

**Comment by wangtao0101** [comment]
@hitbear518 Thank you, I had pushed a new verion, you can update the extension in vscode and try.
